load("@rules_kotlin//kotlin:jvm.bzl", "kt_jvm_binary", "kt_jvm_test")
load(":deps.bzl", "MODULE_DEPS", "TEST_DEPS")

package(default_visibility = ["//visibility:public"])

kt_jvm_binary(
    name = "main",
    srcs = glob(["src/main/kotlin/**/*.kt"]),
    resources = glob(["src/main/resources/**"]),
    main_class = "hs.kr.entrydsm.notification.NotificationBootstrapApplicationKt",
    plugins = ["//:spring_allopen"],
    deps = MODULE_DEPS + [
        "//systems/notification/notification-adapter-in:main",
        "//systems/notification/notification-adapter-out:main",
        "//systems/notification/notification-application:main",
        "//systems/notification/notification-domain:main",
    ],
    javac_opts = "//:javac_options",
    kotlinc_opts = "//:kotlinc_options",
)

kt_jvm_test(
    name = "test",
    srcs = glob(["src/test/kotlin/**/*.kt"]),
    test_class = "hs.kr.entrydsm.notification.NotificationBootstrapApplicationTest",
    plugins = ["//:spring_allopen"],
    deps = MODULE_DEPS + TEST_DEPS,
    javac_opts = "//:javac_options",
    kotlinc_opts = "//:kotlinc_options",
)
