load(
    "//:kotlin.bzl",
    "setup_jpa_allopen_plugin",
    "setup_jpa_noarg_plugin",
    "setup_kotlin_compiler",
    "setup_spring_allopen_plugin",
)

package(default_visibility = ["//visibility:public"])

setup_kotlin_compiler()

setup_spring_allopen_plugin(target_name = "spring_allopen")

setup_jpa_allopen_plugin(target_name = "spring_allopen")

setup_jpa_noarg_plugin()

alias(
    name = "admin",
    actual = "//systems/admin/admin-bootstrap:main",
)

alias(
    name = "application",
    actual = "//systems/application/application-bootstrap:main",
)

alias(
    name = "configuration",
    actual = "//systems/configuration/configuration-bootstrap:main",
)

alias(
    name = "gateway",
    actual = "//systems/gateway/gateway-bootstrap:main",
)

alias(
    name = "identity",
    actual = "//systems/identity/identity-bootstrap:main",
)

alias(
    name = "notification",
    actual = "//systems/notification/notification-bootstrap:main",
)

alias(
    name = "observability",
    actual = "//systems/observability/observability-bootstrap:main",
)
