services:
  redis:
    image: redis:7-alpine
    container_name: entrydsm-redis
    restart: always

  platform:
    image: ghcr.io/entrydsm/entrydsm-platform:latest
    container_name: entrydsm-platform
    env_file:
      - ./.env.platform
    volumes:
      - ./secrets/pass-license.dat:/run/secrets/pass-license.dat:ro
    ports:
      - "8080:8080"
    depends_on:
      - redis
    restart: always
