load("@rules_kotlin//kotlin:jvm.bzl", "kt_jvm_binary", "kt_jvm_test")
load(":deps.bzl", "MODULE_DEPS", "TEST_DEPS")

package(default_visibility = ["//visibility:public"])

kt_jvm_binary(
    name = "main",
    srcs = glob(["src/main/kotlin/**/*.kt"]),
    javac_opts = "//:javac_options",
    kotlinc_opts = "//:kotlinc_options",
    main_class = "hs.kr.entrydsm.gateway.GatewayBootstrapApplicationKt",
    plugins = ["//:spring_allopen"],
    resources = glob(["src/main/resources/**"]),
    deps = MODULE_DEPS + [
        "//systems/gateway/gateway-adapter-in:main",
        "//systems/gateway/gateway-adapter-out:main",
        "//systems/gateway/gateway-application:main",
        "//systems/gateway/gateway-domain:main",
    ],
)

kt_jvm_test(
    name = "test",
    srcs = glob(["src/test/kotlin/**/*.kt"]),
    javac_opts = "//:javac_options",
    kotlinc_opts = "//:kotlinc_options",
    plugins = ["//:spring_allopen"],
    test_class = "hs.kr.entrydsm.gateway.GatewayBootstrapApplicationTest",
    deps = MODULE_DEPS + TEST_DEPS,
)
