load("@rules_kotlin//kotlin:jvm.bzl", "kt_jvm_library", "kt_jvm_test")
load(":deps.bzl", "MODULE_DEPS", "TEST_DEPS")

package(default_visibility = ["//visibility:public"])

kt_jvm_library(
    name = "main",
    srcs = glob(["src/main/kotlin/**/*.kt"]),
    javac_opts = "//:javac_options",
    kotlinc_opts = "//:kotlinc_options",
    deps = MODULE_DEPS,
)

kt_jvm_test(
    name = "test",
    srcs = glob(["src/test/kotlin/**/*.kt"]),
    javac_opts = "//:javac_options",
    kotlinc_opts = "//:kotlinc_options",
    test_class = "hs.kr.entrydsm.admin.domain.AdminDomainModuleTest",
    deps = MODULE_DEPS + TEST_DEPS + [":main"],
)

kt_jvm_test(
    name = "admission_ticket_html_test",
    srcs = glob(["src/test/kotlin/**/*.kt"]),
    javac_opts = "//:javac_options",
    kotlinc_opts = "//:kotlinc_options",
    test_class = "hs.kr.entrydsm.admin.domain.AdmissionTicketHtmlTest",
    deps = MODULE_DEPS + TEST_DEPS + [":main"],
)

kt_jvm_test(
    name = "score_policy_test",
    srcs = glob(["src/test/kotlin/**/*.kt"]),
    javac_opts = "//:javac_options",
    kotlinc_opts = "//:kotlinc_options",
    test_class = "hs.kr.entrydsm.admin.domain.ScorePolicyTest",
    deps = MODULE_DEPS + TEST_DEPS + [":main"],
)

kt_jvm_test(
    name = "admin_policy_test",
    srcs = glob(["src/test/kotlin/**/*.kt"]),
    javac_opts = "//:javac_options",
    kotlinc_opts = "//:kotlinc_options",
    test_class = "hs.kr.entrydsm.admin.domain.AdminPolicyTest",
    deps = MODULE_DEPS + TEST_DEPS + [":main"],
)
