load("@rules_kotlin//kotlin:jvm.bzl", "kt_jvm_library")
load(":deps.bzl", "MODULE_DEPS")

package(default_visibility = ["//visibility:public"])

kt_jvm_library(
    name = "main",
    srcs = glob(["src/main/kotlin/**/*.kt"]),
    javac_opts = "//:javac_options",
    kotlinc_opts = "//:kotlinc_options",
    deps = MODULE_DEPS,
)

