load("@rules_kotlin//kotlin:jvm.bzl", "kt_jvm_library", "kt_jvm_test")
load(":deps.bzl", "MODULE_DEPS", "TEST_DEPS")

package(default_visibility = ["//visibility:public"])

kt_jvm_library(
    name = "main",
    srcs = glob(["src/main/kotlin/**/*.kt"]),
    javac_opts = "//:javac_options",
    kotlinc_opts = "//:kotlinc_options",
    # JPA 엔티티에 인자 없는 생성자를 만들어 준다.
    plugins = ["//:jpa_noarg"],
    resources = glob(["src/main/resources/**"]),
    deps = MODULE_DEPS,
)

kt_jvm_test(
    name = "test",
    srcs = glob(["src/test/kotlin/**/*.kt"]),
    javac_opts = "//:javac_options",
    kotlinc_opts = "//:kotlinc_options",
    test_class = "hs.kr.entrydsm.admin.adapterout.AdminAdapterOutModuleTest",
    deps = MODULE_DEPS + TEST_DEPS + [":main"],
)

kt_jvm_test(
    name = "admission_ticket_pdf_test",
    srcs = glob(["src/test/kotlin/**/*.kt"]),
    javac_opts = "//:javac_options",
    kotlinc_opts = "//:kotlinc_options",
    test_class = "hs.kr.entrydsm.admin.adapterout.document.AdmissionTicketPdfTest",
    deps = MODULE_DEPS + TEST_DEPS + [":main"],
)
