load("@grpc-java//:java_grpc_library.bzl", "java_grpc_library")
load("@rules_java//java:defs.bzl", "java_proto_library")

package(default_visibility = ["//visibility:public"])

alias(
    name = "configuration_proto",
    actual = "//contracts/proto:entrydsm_configuration_v1_proto",
)

java_proto_library(
    name = "configuration_java_proto",
    deps = [":configuration_proto"],
)

java_grpc_library(
    name = "configuration_grpc_java",
    srcs = [":configuration_proto"],
    deps = [":configuration_java_proto"],
)
