load("@grpc-java//:java_grpc_library.bzl", "java_grpc_library")
load("@rules_java//java:defs.bzl", "java_proto_library")

package(default_visibility = ["//visibility:public"])

alias(
    name = "application_proto",
    actual = "//contracts/proto:entrydsm_application_v1_proto",
)

java_proto_library(
    name = "application_java_proto",
    deps = [":application_proto"],
)

java_grpc_library(
    name = "application_grpc_java",
    srcs = [":application_proto"],
    deps = [":application_java_proto"],
)

alias(
    name = "configuration_proto",
    actual = "//contracts/proto:entrydsm_configuration_v1_proto",
)

java_proto_library(
    name = "configuration_java_proto",
    deps = [":configuration_proto"],
)

java_grpc_library(
    name = "configuration_grpc_java",
    srcs = [":configuration_proto"],
    deps = [":configuration_java_proto"],
)

alias(
    name = "notification_proto",
    actual = "//contracts/proto:entrydsm_notification_v1_proto",
)

java_proto_library(
    name = "notification_java_proto",
    deps = [":notification_proto"],
)

java_grpc_library(
    name = "notification_grpc_java",
    srcs = [":notification_proto"],
    deps = [":notification_java_proto"],
)
