package hs.kr.entrydsm.application.application.exception

enum class ApplicationErrorCode(
    val field: String,
    val reason: String,
    val message: String,
) {
    APPLICATION_PHOTO_FILE_ID_REQUIRED("photoFileId", "REQUIRED", "증명사진 파일 ID 항목을 입력해주세요."),
    APPLICATION_PHOTO_FILE_ID_INVALID_TYPE("photoFileId", "INVALID_TYPE", "증명사진 파일 ID 항목의 데이터 형식을 확인해주세요."),
    APPLICATION_NAME_REQUIRED("name", "REQUIRED", "이름 항목을 입력해주세요."),
    APPLICATION_NAME_INVALID_TYPE("name", "INVALID_TYPE", "이름 항목의 데이터 형식을 확인해주세요."),
    APPLICATION_NAME_TOO_LONG("name", "TOO_LONG", "이름 항목은 20자 이내로 입력해주세요."),
    APPLICATION_PHONE_NUMBER_REQUIRED("phoneNumber", "REQUIRED", "전화번호 항목을 입력해주세요."),
    APPLICATION_PHONE_NUMBER_INVALID_TYPE("phoneNumber", "INVALID_TYPE", "전화번호 항목의 데이터 형식을 확인해주세요."),
    APPLICATION_PHONE_NUMBER_INVALID_FORMAT("phoneNumber", "INVALID_FORMAT", "전화번호 항목은 010-0000-0000 형식으로 입력해주세요."),
    APPLICATION_PHONE_NUMBER_MISMATCH("phoneNumber", "MISMATCH", "가입한 전화번호와 입력한 전화번호가 일치하지 않습니다."),
    APPLICATION_GENDER_REQUIRED("gender", "REQUIRED", "성별 항목을 입력해주세요."),
    APPLICATION_GENDER_INVALID_TYPE("gender", "INVALID_TYPE", "성별 항목의 데이터 형식을 확인해주세요."),
    APPLICATION_GENDER_INVALID_VALUE("gender", "INVALID_VALUE", "성별 항목에 허용된 값을 입력해주세요."),
    APPLICATION_BIRTHDATE_REQUIRED("birthdate", "REQUIRED", "생년월일 항목을 입력해주세요."),
    APPLICATION_BIRTHDATE_INVALID_TYPE("birthdate", "INVALID_TYPE", "생년월일 항목의 데이터 형식을 확인해주세요."),
    APPLICATION_BIRTHDATE_INVALID_FORMAT("birthdate", "INVALID_FORMAT", "생년월일 항목은 유효한 YYYY-MM 또는 YYYY-MM-DD 형식으로 입력해주세요."),
    APPLICATION_SPECIAL_ADMISSION_TYPE_REQUIRED("specialAdmissionType", "REQUIRED", "특별전형 구분 항목을 입력해주세요."),
    APPLICATION_SPECIAL_ADMISSION_TYPE_INVALID_TYPE("specialAdmissionType", "INVALID_TYPE", "특별전형 구분 항목의 데이터 형식을 확인해주세요."),
    APPLICATION_SPECIAL_ADMISSION_TYPE_INVALID_VALUE("specialAdmissionType", "INVALID_VALUE", "특별전형 구분 항목에 허용된 값을 입력해주세요."),
    APPLICATION_ADMISSION_TYPE_REQUIRED("admissionType", "REQUIRED", "전형 항목을 입력해주세요."),
    APPLICATION_ADMISSION_TYPE_INVALID_TYPE("admissionType", "INVALID_TYPE", "전형 항목의 데이터 형식을 확인해주세요."),
    APPLICATION_ADMISSION_TYPE_INVALID_VALUE("admissionType", "INVALID_VALUE", "전형 항목에 허용된 값을 입력해주세요."),
    APPLICATION_REGION_REQUIRED("region", "REQUIRED", "지역 항목을 입력해주세요."),
    APPLICATION_REGION_INVALID_TYPE("region", "INVALID_TYPE", "지역 항목의 데이터 형식을 확인해주세요."),
    APPLICATION_REGION_INVALID_VALUE("region", "INVALID_VALUE", "지역 항목에 허용된 값을 입력해주세요."),
    APPLICATION_GRADUATION_TYPE_REQUIRED("graduationType", "REQUIRED", "졸업 구분 항목을 입력해주세요."),
    APPLICATION_GRADUATION_TYPE_INVALID_TYPE("graduationType", "INVALID_TYPE", "졸업 구분 항목의 데이터 형식을 확인해주세요."),
    APPLICATION_GRADUATION_TYPE_INVALID_VALUE("graduationType", "INVALID_VALUE", "졸업 구분 항목에 허용된 값을 입력해주세요."),
    APPLICATION_GRADUATION_DATE_REQUIRED("graduationDate", "REQUIRED", "졸업년월 항목을 입력해주세요."),
    APPLICATION_GRADUATION_DATE_INVALID_TYPE("graduationDate", "INVALID_TYPE", "졸업년월 항목의 데이터 형식을 확인해주세요."),
    APPLICATION_GRADUATION_DATE_INVALID_FORMAT("graduationDate", "INVALID_FORMAT", "졸업년월 항목은 유효한 YYYY-MM 형식으로 입력해주세요."),
    APPLICATION_GRADUATION_DATE_OUT_OF_RANGE("graduationDate", "OUT_OF_RANGE", "졸업년월의 연도는 2026 또는 2027로 입력해주세요."),
    APPLICATION_GUARDIAN_NAME_REQUIRED("guardianName", "REQUIRED", "보호자 이름 항목을 입력해주세요."),
    APPLICATION_GUARDIAN_NAME_INVALID_TYPE("guardianName", "INVALID_TYPE", "보호자 이름 항목의 데이터 형식을 확인해주세요."),
    APPLICATION_GUARDIAN_NAME_TOO_LONG("guardianName", "TOO_LONG", "보호자 이름 항목은 20자 이내로 입력해주세요."),
    APPLICATION_GUARDIAN_PHONE_NUMBER_REQUIRED("guardianPhoneNumber", "REQUIRED", "보호자 전화번호 항목을 입력해주세요."),
    APPLICATION_GUARDIAN_PHONE_NUMBER_INVALID_TYPE("guardianPhoneNumber", "INVALID_TYPE", "보호자 전화번호 항목의 데이터 형식을 확인해주세요."),
    APPLICATION_GUARDIAN_PHONE_NUMBER_INVALID_FORMAT("guardianPhoneNumber", "INVALID_FORMAT", "보호자 전화번호 항목은 010-0000-0000 형식으로 입력해주세요."),
    APPLICATION_GUARDIAN_GENDER_REQUIRED("guardianGender", "REQUIRED", "보호자 성별 항목을 입력해주세요."),
    APPLICATION_GUARDIAN_GENDER_INVALID_TYPE("guardianGender", "INVALID_TYPE", "보호자 성별 항목의 데이터 형식을 확인해주세요."),
    APPLICATION_GUARDIAN_GENDER_INVALID_VALUE("guardianGender", "INVALID_VALUE", "보호자 성별 항목에 허용된 값을 입력해주세요."),
    APPLICATION_GUARDIAN_RELATION_REQUIRED("guardianRelation", "REQUIRED", "보호자 관계 항목을 입력해주세요."),
    APPLICATION_GUARDIAN_RELATION_INVALID_TYPE("guardianRelation", "INVALID_TYPE", "보호자 관계 항목의 데이터 형식을 확인해주세요."),
    APPLICATION_ADDRESS_REQUIRED("address", "REQUIRED", "주소 항목을 입력해주세요."),
    APPLICATION_ADDRESS_INVALID_TYPE("address", "INVALID_TYPE", "주소 항목의 데이터 형식을 확인해주세요."),
    APPLICATION_ADDRESS_ZIP_CODE_REQUIRED("address.zipCode", "REQUIRED", "우편번호 항목을 입력해주세요."),
    APPLICATION_ADDRESS_ZIP_CODE_INVALID_TYPE("address.zipCode", "INVALID_TYPE", "우편번호 항목의 데이터 형식을 확인해주세요."),
    APPLICATION_ADDRESS_ZIP_CODE_TOO_LONG("address.zipCode", "TOO_LONG", "우편번호 항목은 10자 이내로 입력해주세요."),
    APPLICATION_ADDRESS_ADDRESS_BASE_REQUIRED("address.addressBase", "REQUIRED", "기본 주소 항목을 입력해주세요."),
    APPLICATION_ADDRESS_ADDRESS_BASE_INVALID_TYPE("address.addressBase", "INVALID_TYPE", "기본 주소 항목의 데이터 형식을 확인해주세요."),
    APPLICATION_ADDRESS_ADDRESS_BASE_TOO_LONG("address.addressBase", "TOO_LONG", "기본 주소 항목은 255자 이내로 입력해주세요."),
    APPLICATION_ADDRESS_ADDRESS_DETAIL_REQUIRED("address.addressDetail", "REQUIRED", "상세 주소 항목을 입력해주세요."),
    APPLICATION_ADDRESS_ADDRESS_DETAIL_INVALID_TYPE("address.addressDetail", "INVALID_TYPE", "상세 주소 항목의 데이터 형식을 확인해주세요."),
    APPLICATION_ADDRESS_ADDRESS_DETAIL_TOO_LONG("address.addressDetail", "TOO_LONG", "상세 주소 항목은 255자 이내로 입력해주세요."),
    APPLICATION_SCHOOL_CODE_REQUIRED("schoolCode", "REQUIRED", "학교 코드 항목을 입력해주세요."),
    APPLICATION_SCHOOL_CODE_INVALID_TYPE("schoolCode", "INVALID_TYPE", "학교 코드 항목의 데이터 형식을 확인해주세요."),
    APPLICATION_SCHOOL_CODE_TOO_LONG("schoolCode", "TOO_LONG", "학교 코드 항목은 20자 이내로 입력해주세요."),
    APPLICATION_SCHOOL_NAME_REQUIRED("schoolName", "REQUIRED", "학교 이름 항목을 입력해주세요."),
    APPLICATION_SCHOOL_NAME_INVALID_TYPE("schoolName", "INVALID_TYPE", "학교 이름 항목의 데이터 형식을 확인해주세요."),
    APPLICATION_SCHOOL_NAME_TOO_LONG("schoolName", "TOO_LONG", "학교 이름 항목은 50자 이내로 입력해주세요."),
    APPLICATION_STUDENT_NUMBER_REQUIRED("studentNumber", "REQUIRED", "학번 항목을 입력해주세요."),
    APPLICATION_STUDENT_NUMBER_INVALID_TYPE("studentNumber", "INVALID_TYPE", "학번 항목의 데이터 형식을 확인해주세요."),
    APPLICATION_STUDENT_NUMBER_TOO_LONG("studentNumber", "TOO_LONG", "학번 항목은 8자 이내로 입력해주세요."),
    APPLICATION_STUDENT_NUMBER_INVALID_FORMAT("studentNumber", "INVALID_FORMAT", "학번은 5자리 숫자로 입력해주세요."),
    APPLICATION_STUDENT_NUMBER_OUT_OF_RANGE("studentNumber", "OUT_OF_RANGE", "중학교 학년은 1~3, 반과 번호는 각각 01~99 사이로 입력해주세요."),
    APPLICATION_SCHOOL_PHONE_REQUIRED("schoolPhone", "REQUIRED", "학교 전화번호 항목을 입력해주세요."),
    APPLICATION_SCHOOL_PHONE_INVALID_TYPE("schoolPhone", "INVALID_TYPE", "학교 전화번호 항목의 데이터 형식을 확인해주세요."),
    APPLICATION_SCHOOL_PHONE_TOO_LONG("schoolPhone", "TOO_LONG", "학교 전화번호 항목은 16자 이내로 입력해주세요."),
    APPLICATION_TEACHER_NAME_REQUIRED("teacherName", "REQUIRED", "담임교사 이름 항목을 입력해주세요."),
    APPLICATION_TEACHER_NAME_INVALID_TYPE("teacherName", "INVALID_TYPE", "담임교사 이름 항목의 데이터 형식을 확인해주세요."),
    APPLICATION_TEACHER_NAME_TOO_LONG("teacherName", "TOO_LONG", "담임교사 이름 항목은 20자 이내로 입력해주세요."),
    APPLICATION_INTRODUCTION_REQUIRED("introduction", "REQUIRED", "자기소개서 항목을 입력해주세요."),
    APPLICATION_INTRODUCTION_INVALID_TYPE("introduction", "INVALID_TYPE", "자기소개서 항목의 데이터 형식을 확인해주세요."),
    APPLICATION_INTRODUCTION_TOO_LONG("introduction", "TOO_LONG", "자기소개서 항목은 1600자 이내로 입력해주세요."),
    APPLICATION_STUDY_PLAN_REQUIRED("studyPlan", "REQUIRED", "학업계획서 항목을 입력해주세요."),
    APPLICATION_STUDY_PLAN_INVALID_TYPE("studyPlan", "INVALID_TYPE", "학업계획서 항목의 데이터 형식을 확인해주세요."),
    APPLICATION_STUDY_PLAN_TOO_LONG("studyPlan", "TOO_LONG", "학업계획서 항목은 1600자 이내로 입력해주세요."),
    APPLICATION_SCHOOL_SEMESTER_REQUIRED("schoolSemester", "REQUIRED", "학기 항목을 입력해주세요."),
    APPLICATION_SCHOOL_SEMESTER_INVALID_TYPE("schoolSemester", "INVALID_TYPE", "학기 항목의 데이터 형식을 확인해주세요."),
    APPLICATION_SCHOOL_SEMESTER_INVALID_VALUE("schoolSemester", "INVALID_VALUE", "학기 항목에 허용된 값을 입력해주세요."),
    APPLICATION_SUBJECTS_REQUIRED("subjects", "REQUIRED", "과목 성적 항목을 입력해주세요."),
    APPLICATION_SUBJECTS_INVALID_TYPE("subjects", "INVALID_TYPE", "과목 성적 항목의 데이터 형식을 확인해주세요."),
    APPLICATION_KOREAN_SCORE_REQUIRED("koreanScore", "REQUIRED", "검정고시 국어 점수 항목을 입력해주세요."),
    APPLICATION_KOREAN_SCORE_INVALID_TYPE("koreanScore", "INVALID_TYPE", "검정고시 국어 점수 항목의 데이터 형식을 확인해주세요."),
    APPLICATION_KOREAN_SCORE_OUT_OF_RANGE("koreanScore", "OUT_OF_RANGE", "검정고시 국어 점수 항목은 0~100 사이로 입력해주세요."),
    APPLICATION_SUBJECTS_KOREAN_GRADE_REQUIRED("subjects.koreanGrade", "REQUIRED", "국어 성적 항목을 입력해주세요."),
    APPLICATION_SUBJECTS_KOREAN_GRADE_INVALID_TYPE("subjects.koreanGrade", "INVALID_TYPE", "국어 성적 항목의 데이터 형식을 확인해주세요."),
    APPLICATION_SUBJECTS_KOREAN_GRADE_INVALID_VALUE("subjects.koreanGrade", "INVALID_VALUE", "국어 성적 항목에 허용된 값을 입력해주세요."),
    APPLICATION_MATH_SCORE_REQUIRED("mathScore", "REQUIRED", "검정고시 수학 점수 항목을 입력해주세요."),
    APPLICATION_MATH_SCORE_INVALID_TYPE("mathScore", "INVALID_TYPE", "검정고시 수학 점수 항목의 데이터 형식을 확인해주세요."),
    APPLICATION_MATH_SCORE_OUT_OF_RANGE("mathScore", "OUT_OF_RANGE", "검정고시 수학 점수 항목은 0~100 사이로 입력해주세요."),
    APPLICATION_SUBJECTS_MATH_GRADE_REQUIRED("subjects.mathGrade", "REQUIRED", "수학 성적 항목을 입력해주세요."),
    APPLICATION_SUBJECTS_MATH_GRADE_INVALID_TYPE("subjects.mathGrade", "INVALID_TYPE", "수학 성적 항목의 데이터 형식을 확인해주세요."),
    APPLICATION_SUBJECTS_MATH_GRADE_INVALID_VALUE("subjects.mathGrade", "INVALID_VALUE", "수학 성적 항목에 허용된 값을 입력해주세요."),
    APPLICATION_ENGLISH_SCORE_REQUIRED("englishScore", "REQUIRED", "검정고시 영어 점수 항목을 입력해주세요."),
    APPLICATION_ENGLISH_SCORE_INVALID_TYPE("englishScore", "INVALID_TYPE", "검정고시 영어 점수 항목의 데이터 형식을 확인해주세요."),
    APPLICATION_ENGLISH_SCORE_OUT_OF_RANGE("englishScore", "OUT_OF_RANGE", "검정고시 영어 점수 항목은 0~100 사이로 입력해주세요."),
    APPLICATION_SUBJECTS_ENGLISH_GRADE_REQUIRED("subjects.englishGrade", "REQUIRED", "영어 성적 항목을 입력해주세요."),
    APPLICATION_SUBJECTS_ENGLISH_GRADE_INVALID_TYPE("subjects.englishGrade", "INVALID_TYPE", "영어 성적 항목의 데이터 형식을 확인해주세요."),
    APPLICATION_SUBJECTS_ENGLISH_GRADE_INVALID_VALUE("subjects.englishGrade", "INVALID_VALUE", "영어 성적 항목에 허용된 값을 입력해주세요."),
    APPLICATION_SCIENCE_SCORE_REQUIRED("scienceScore", "REQUIRED", "검정고시 과학 점수 항목을 입력해주세요."),
    APPLICATION_SCIENCE_SCORE_INVALID_TYPE("scienceScore", "INVALID_TYPE", "검정고시 과학 점수 항목의 데이터 형식을 확인해주세요."),
    APPLICATION_SCIENCE_SCORE_OUT_OF_RANGE("scienceScore", "OUT_OF_RANGE", "검정고시 과학 점수 항목은 0~100 사이로 입력해주세요."),
    APPLICATION_SUBJECTS_SCIENCE_GRADE_REQUIRED("subjects.scienceGrade", "REQUIRED", "과학 성적 항목을 입력해주세요."),
    APPLICATION_SUBJECTS_SCIENCE_GRADE_INVALID_TYPE("subjects.scienceGrade", "INVALID_TYPE", "과학 성적 항목의 데이터 형식을 확인해주세요."),
    APPLICATION_SUBJECTS_SCIENCE_GRADE_INVALID_VALUE("subjects.scienceGrade", "INVALID_VALUE", "과학 성적 항목에 허용된 값을 입력해주세요."),
    APPLICATION_SOCIETY_SCORE_REQUIRED("societyScore", "REQUIRED", "검정고시 사회 점수 항목을 입력해주세요."),
    APPLICATION_SOCIETY_SCORE_INVALID_TYPE("societyScore", "INVALID_TYPE", "검정고시 사회 점수 항목의 데이터 형식을 확인해주세요."),
    APPLICATION_SOCIETY_SCORE_OUT_OF_RANGE("societyScore", "OUT_OF_RANGE", "검정고시 사회 점수 항목은 0~100 사이로 입력해주세요."),
    APPLICATION_SUBJECTS_SOCIETY_GRADE_REQUIRED("subjects.societyGrade", "REQUIRED", "사회 성적 항목을 입력해주세요."),
    APPLICATION_SUBJECTS_SOCIETY_GRADE_INVALID_TYPE("subjects.societyGrade", "INVALID_TYPE", "사회 성적 항목의 데이터 형식을 확인해주세요."),
    APPLICATION_SUBJECTS_SOCIETY_GRADE_INVALID_VALUE("subjects.societyGrade", "INVALID_VALUE", "사회 성적 항목에 허용된 값을 입력해주세요."),
    APPLICATION_TECHNOLOGY_SCORE_REQUIRED("technologyScore", "REQUIRED", "검정고시 기술 점수 항목을 입력해주세요."),
    APPLICATION_TECHNOLOGY_SCORE_INVALID_TYPE("technologyScore", "INVALID_TYPE", "검정고시 기술 점수 항목의 데이터 형식을 확인해주세요."),
    APPLICATION_TECHNOLOGY_SCORE_OUT_OF_RANGE("technologyScore", "OUT_OF_RANGE", "검정고시 기술 점수 항목은 0~100 사이로 입력해주세요."),
    APPLICATION_SUBJECTS_TECHNOLOGY_GRADE_REQUIRED("subjects.technologyGrade", "REQUIRED", "기술 성적 항목을 입력해주세요."),
    APPLICATION_SUBJECTS_TECHNOLOGY_GRADE_INVALID_TYPE("subjects.technologyGrade", "INVALID_TYPE", "기술 성적 항목의 데이터 형식을 확인해주세요."),
    APPLICATION_SUBJECTS_TECHNOLOGY_GRADE_INVALID_VALUE("subjects.technologyGrade", "INVALID_VALUE", "기술 성적 항목에 허용된 값을 입력해주세요."),
    APPLICATION_HISTORY_SCORE_REQUIRED("historyScore", "REQUIRED", "검정고시 역사 점수 항목을 입력해주세요."),
    APPLICATION_HISTORY_SCORE_INVALID_TYPE("historyScore", "INVALID_TYPE", "검정고시 역사 점수 항목의 데이터 형식을 확인해주세요."),
    APPLICATION_HISTORY_SCORE_OUT_OF_RANGE("historyScore", "OUT_OF_RANGE", "검정고시 역사 점수 항목은 0~100 사이로 입력해주세요."),
    APPLICATION_SUBJECTS_HISTORY_GRADE_REQUIRED("subjects.historyGrade", "REQUIRED", "역사 성적 항목을 입력해주세요."),
    APPLICATION_SUBJECTS_HISTORY_GRADE_INVALID_TYPE("subjects.historyGrade", "INVALID_TYPE", "역사 성적 항목의 데이터 형식을 확인해주세요."),
    APPLICATION_SUBJECTS_HISTORY_GRADE_INVALID_VALUE("subjects.historyGrade", "INVALID_VALUE", "역사 성적 항목에 허용된 값을 입력해주세요."),
    APPLICATION_ABSENT_COUNT_REQUIRED("absentCount", "REQUIRED", "결석 일수 항목을 입력해주세요."),
    APPLICATION_ABSENT_COUNT_INVALID_TYPE("absentCount", "INVALID_TYPE", "결석 일수 항목의 데이터 형식을 확인해주세요."),
    APPLICATION_ABSENT_COUNT_OUT_OF_RANGE("absentCount", "OUT_OF_RANGE", "결석 일수 항목은 0 이상으로 입력해주세요."),
    APPLICATION_LATE_COUNT_REQUIRED("lateCount", "REQUIRED", "지각 횟수 항목을 입력해주세요."),
    APPLICATION_LATE_COUNT_INVALID_TYPE("lateCount", "INVALID_TYPE", "지각 횟수 항목의 데이터 형식을 확인해주세요."),
    APPLICATION_LATE_COUNT_OUT_OF_RANGE("lateCount", "OUT_OF_RANGE", "지각 횟수 항목은 0 이상으로 입력해주세요."),
    APPLICATION_EARLY_LEAVE_COUNT_REQUIRED("earlyLeaveCount", "REQUIRED", "조퇴 횟수 항목을 입력해주세요."),
    APPLICATION_EARLY_LEAVE_COUNT_INVALID_TYPE("earlyLeaveCount", "INVALID_TYPE", "조퇴 횟수 항목의 데이터 형식을 확인해주세요."),
    APPLICATION_EARLY_LEAVE_COUNT_OUT_OF_RANGE("earlyLeaveCount", "OUT_OF_RANGE", "조퇴 횟수 항목은 0 이상으로 입력해주세요."),
    APPLICATION_CLASS_ABSENCE_COUNT_REQUIRED("classAbsenceCount", "REQUIRED", "결과 횟수 항목을 입력해주세요."),
    APPLICATION_CLASS_ABSENCE_COUNT_INVALID_TYPE("classAbsenceCount", "INVALID_TYPE", "결과 횟수 항목의 데이터 형식을 확인해주세요."),
    APPLICATION_CLASS_ABSENCE_COUNT_OUT_OF_RANGE("classAbsenceCount", "OUT_OF_RANGE", "결과 횟수 항목은 0 이상으로 입력해주세요."),
    APPLICATION_VOLUNTEER_TIME_REQUIRED("volunteerTime", "REQUIRED", "봉사시간 항목을 입력해주세요."),
    APPLICATION_VOLUNTEER_TIME_INVALID_TYPE("volunteerTime", "INVALID_TYPE", "봉사시간 항목의 데이터 형식을 확인해주세요."),
    APPLICATION_VOLUNTEER_TIME_OUT_OF_RANGE("volunteerTime", "OUT_OF_RANGE", "봉사시간 항목은 0 이상으로 입력해주세요."),
    APPLICATION_IS_DSM_ALGORITHM_AWARDED_REQUIRED("isDsmAlgorithmAwarded", "REQUIRED", "DSM 알고리즘 대회 수상 여부 항목을 입력해주세요."),
    APPLICATION_IS_DSM_ALGORITHM_AWARDED_INVALID_TYPE("isDsmAlgorithmAwarded", "INVALID_TYPE", "DSM 알고리즘 대회 수상 여부 항목의 데이터 형식을 확인해주세요."),
    APPLICATION_IS_PROGRAMMING_CERTIFIED_REQUIRED("isProgrammingCertified", "REQUIRED", "프로그래밍 자격증 보유 여부 항목을 입력해주세요."),
    APPLICATION_IS_PROGRAMMING_CERTIFIED_INVALID_TYPE("isProgrammingCertified", "INVALID_TYPE", "프로그래밍 자격증 보유 여부 항목의 데이터 형식을 확인해주세요."),
    APPLICATION_PHOTO_FILE_ID_TOO_LONG("photoFileId", "TOO_LONG", "증명사진 파일 ID는 64자 이내로 입력해주세요."),
    APPLICATION_GRADUATION_DATE_NOT_ALLOWED("graduationDate", "NOT_ALLOWED", "검정고시 지원자는 졸업년월을 입력할 수 없습니다."),
    APPLICATION_MIDDLE_SCHOOL_NOT_ALLOWED("middleSchool", "NOT_ALLOWED", "검정고시 지원자는 출신학교 정보를 입력할 수 없습니다."),
    APPLICATION_SUBJECTS_NOT_ALLOWED("subjects", "NOT_ALLOWED", "검정고시 지원자는 학교 성적을 입력할 수 없습니다."),
    APPLICATION_GED_SCORES_NOT_ALLOWED("gedScores", "NOT_ALLOWED", "검정고시 점수는 검정고시 지원자만 입력할 수 있습니다."),
    APPLICATION_NOT_EDITABLE("status", "NOT_ALLOWED", "작성 중인 원서만 수정할 수 있습니다.");

    fun requireValid(condition: Boolean) {
        if (!condition) throw ApplicationValidationException(this)
    }

    companion object {
        fun find(field: String, reason: String): ApplicationErrorCode? =
            entries.firstOrNull { it.field == field && it.reason == reason }
    }
}
