load("@rules_kotlin//kotlin:jvm.bzl", "kt_jvm_library", "kt_jvm_test")
load("//:kotlin.bzl", "jpa_allopen_plugins")
load(":deps.bzl", "MODULE_DEPS", "TEST_DEPS")

package(default_visibility = ["//visibility:public"])

java_import(
    name = "okcert",
    jars = ["libs/OkCert3-java1.5-2.3.1.jar"],
)

kt_jvm_library(
    name = "main",
    srcs = glob(["src/main/kotlin/**/*.kt"]),
    javac_opts = "//:javac_options",
    kotlinc_opts = "//:kotlinc_options",
    plugins = jpa_allopen_plugins(target_name = "spring_allopen"),
    deps = MODULE_DEPS + [":okcert"],
)

kt_jvm_test(
    name = "test",
    srcs = glob(["src/test/kotlin/**/*.kt"]),
    javac_opts = "//:javac_options",
    kotlinc_opts = "//:kotlinc_options",
    test_class = "hs.kr.entrydsm.identity.adapterout.IdentityAdapterOutModuleTest",
    deps = [":main"] + MODULE_DEPS + TEST_DEPS + [
        "//systems/identity/identity-test-support:main",
    ],
)
